### ISSUE TITLE
Migration guide for moving from v1 to v2.

### ISSUE THREAD

**Issue by espenaf** [kantega/reststop#13]
Wiki page for migration: https://github.com/kantega/reststop/wiki/Migrating-from-v1-to-v2

**Comment by eirbjo** [comment]
Moved this here and added some notes describing what has been removed and what the replacements are: https://github.com/kantega/reststop/wiki/Migrating-to-Reststop-2

**Comment by espenaf** [comment]
I would really like to see some examples of migrating addServletFilter() and createServletFilter() to ServletBuilder.class.

**Comment by eirbjo** [comment]
Migration guide now includes a link to an example from the hello-world integration test.
