### ISSUE TITLE
Jetty startup warning 

### ISSUE THREAD

**Issue by helaar** [kantega/reststop#24]
org.eclipse.jetty.server.HomeBaseWarning This instance of Jetty is not running from a separate {jetty.base} directory, this is not recommended.  See documentation at http://www.eclipse.org/jetty/documentation/current/startup.html

**Comment by eirbjo** [comment]
Jetty-distribution is probably too heavy-weight for us anyway. I've taken a note about replacing it for the  Reststop 3 roadmap: https://github.com/kantega/reststop/wiki/Roadmap
