### ISSUE TITLE
Unclear failure message

### ISSUE THREAD

**Issue by prange** [kantega/reststop#3]
When starting Reststop, the following message was issued by maven:
````
[ERROR] Plugin org.kantega-helloworld:1.0-SNAPSHOT depends on plugin org.kantega.reststop:reststop-jaxrs-api:1.10 which must be declared as a <plugin>!
[ERROR] Please add the following to your <plugins> section:
	<plugin>
		<groupId>org.kantega.reststop</groupId>
		<artifactId>reststop-jaxrs-api</artifactId>
		<version>1.10</version>
	</plugin>
````
It is unclear in what ```pom.xml``` this should be inserted to, as the definition already is in the ```pom.xml``` of the plugin module.

**Comment by prange** [comment]
BTW: The message appeared after i had created a new plugin using mvn restartop:create-plugin. Before that it ran fine.

**Comment by eirbjo** [comment]
Two things: 

1) The error message could be easier to read and should point to the pom.xml that needs to change.
2) reststop:start (and maybe reststop:run) should be considered for removal. Most projects will need a webapp project anyway.

**Comment by eirbjo** [comment]
The new error message reads:

```
[ERROR] Plugin org.kantega.reststop:reststop-jersey-plugin:1.11-SNAPSHOT depends on the plugin org.kantega.reststop:reststop-jaxrs-api:1.11-SNAPSHOT which is not declared as a <plugin> in /Users/eirbjo/Projects/exampleservice/webapp/pom.xml
[ERROR] Please add the following to maven-reststop-plugin's <plugins> section in /Users/eirbjo/Projects/exampleservice/webapp/pom.xml:
	<plugin>
		<groupId>org.kantega.reststop</groupId>
		<artifactId>reststop-jaxrs-api</artifactId>
		<version>1.11-SNAPSHOT</version>
	</plugin>

```
