### ISSUE TITLE
Maven-plugin uses mvn.bat on Windows

### ISSUE THREAD

**Issue by anderius** [kantega/reststop#7]
Newer versions of Maven does not have that file, but uses mvn.cmd.

**Comment by eirbjo** [comment]
Maven uses mvn.cmd, Maven Invoker expects mvn.bat.

Similar issue: https://jira.codehaus.org/browse/MNG-5792

**Comment by eirbjo** [comment]
Fixed (but not released) in maven-invoker 2.3-SNAPSHOT:

https://issues.apache.org/jira/browse/MSHARED-413

**Comment by eirbjo** [comment]
Correction: This was fixed in maven-invoker 2.2. @espenaf has already updated to this version in Reststop. Will be fixed in Reststop 1.12.
